name: buffetd-dev

services:
  postgres:
    image: postgres:17-alpine
    ports:
      - '5532:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  rustfs:
    image: rustfs/rustfs:latest
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - rustfs_data:/data
    environment:
      RUSTFS_ACCESS_KEY: ${RUSTFS_ACCESS_KEY}
      RUSTFS_SECRET_KEY: ${RUSTFS_SECRET_KEY}

  serverless-redis-http:
    image: hiett/serverless-redis-http:latest
    ports:
      - '8079:80'
    environment:
      SRH_MODE: env
      SRH_TOKEN: ${SRH_TOKEN}
      SRH_CONNECTION_STRING: 'redis://redis:6379'
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    ports:
      - '6479:6379'

  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - '1125:1025'
      - '8125:8025'

volumes:
  postgres_data:
  rustfs_data:
